### ISSUE TITLE
Publish buildstream-plugins docs somewhere

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream-plugins#22]
I think the correct location is https://apache.github.io/buildstream-plugins/ but that returns a 404 atm

**Comment by gtristan** [comment]
Yes, that’s where they are published to.

the ci and everything is setup the same way as the BuildStream repository is, but I presume there are some magic hidden settings which are preventing them from appearing online.

**Comment by wsalmonct** [comment]
#24 seems to have resolved this. Ill let @jjardon reslove this in case he can spot anything else

**Comment by jjardon** [comment]
Yeah, It is fixed; thanks!
