### ISSUE TITLE
Complete git history of plugins is missing

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream-plugins#7]
Seems some plugins have been copy and pasted from https://gitlab.com/BuildStream/bst-plugins-experimental/ so all the git history of years of development is lost

A possible solution would be to create a git repo mirroring https://gitlab.com/BuildStream/bst-plugins-experimental/ , then add / remove wherever is needed

Other solution is https://gitlab.com/BuildStream/bst-plugins-experimental/-/issues/46

**Comment by gtristan** [comment]
The history of plugins which were added to this _new_ repo is still available in the respective repositories from whence they came, I don't think this is a problem.

**Comment by jjardon** [comment]
Cool, I think a good compromise would be to document somwhere the origin of the plugins in case someone need to check the history
